# Nivel de Ajuste de un Modelo y Tipos de Error
Un buen ajuste implica capturar patrones sin caer en el sobreajuste ni en el subajuste. Es crucial para lograr predicciones precisas y generalizables.

## Tipos de error para evaluar un modelo:
- **Error de entrenamiento:** Diferencia entre predicciones y valores reales en el conjunto de entrenamiento. Suele ser bajo, pero no garantiza buen rendimiento en datos nuevos.

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [3]:
# Datos de ejemplo para regresión lineal simple
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_train_pred = model.predict(X_train)
training_error = mean_squared_error(y_train, y_train_pred)
training_r2 = r2_score(y_train, y_train_pred)

print(f'Error de Entrenamiento (MSE): {training_error:.4f}')
print(f'R2 de Entrenamiento: {training_r2:.4f}')

Error de Entrenamiento (MSE): 0.8477
R2 de Entrenamiento: 0.7582


## Error de Validación y Error de Prueba
- **Error de validación:** Evalúa el modelo en datos no usados en el entrenamiento. Ayuda a identificar sobreajuste.
- **Error de prueba:** Se mide en un conjunto independiente, reservado hasta el final.

In [4]:
y_val_pred = model.predict(X_test)
validation_error = mean_squared_error(y_test, y_val_pred)
print(f'Error de Validación (MSE): {validation_error:.4f}')
test_error = mean_squared_error(y_test, y_val_pred)
print(f'Error de Prueba (MSE): {test_error:.4f}')
test_r2 = r2_score(y_test, y_val_pred)
print(f'R2 de Prueba: {test_r2:.4f}')

Error de Validación (MSE): 0.6537
Error de Prueba (MSE): 0.6537
R2 de Prueba: 0.8072


## Sobreajuste (Overfitting)
El modelo se ajusta demasiado a los datos de entrenamiento, capturando ruido y anomalías.

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
np.random.seed(0)
X_overfit = np.sort(np.random.rand(100, 1) * 10, axis=0)
y_overfit = np.sin(X_overfit).ravel() + np.random.normal(0, 0.1, X_overfit.shape)
X_train_over, X_test_over, y_train_over, y_test_over = train_test_split(X_overfit, y_overfit, test_size=0.3, random_state=0)

# Modelo sobreajustado
degree = 15
overfit_model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
overfit_model.fit(X_train_over, y_train_over)
train_pred_over = overfit_model.predict(X_train_over)
test_pred_over = overfit_model.predict(X_test_over)
train_error_over = mean_squared_error(y_train_over, train_pred_over)
test_error_over = mean_squared_error(y_test_over, test_pred_over)
print(f'Modelo con grado polinomial {degree} (potencialmente sobreajustado):')
print(f'  Error de Entrenamiento (MSE): {train_error_over:.4f}')
print(f'  Error de Prueba (MSE): {test_error_over:.4f}')
print(f'  R2 de Entrenamiento: {r2_score(y_train_over, train_pred_over):.4f}')
print(f'  R2 de Prueba: {r2_score(y_test_over, test_pred_over):.4f}')

Modelo con grado polinomial 15 (potencialmente sobreajustado):
  Error de Entrenamiento (MSE): 0.0083
  Error de Prueba (MSE): 0.0141
  R2 de Entrenamiento: 0.1643
  R2 de Prueba: -0.4492


## Subajuste (Underfitting) y Ajuste Apropiado
El subajuste ocurre cuando el modelo es demasiado simple. El ajuste apropiado equilibra complejidad y generalización.

In [ ]:
# Modelo subajustado y ajuste apropiado
degree_under = 1
underfit_model = make_pipeline(PolynomialFeatures(degree_under), LinearRegression())
underfit_model.fit(X_train_over, y_train_over)
train_pred_under = underfit_model.predict(X_train_over)
test_pred_under = underfit_model.predict(X_test_over)
train_error_under = mean_squared_error(y_train_over, train_pred_under)
test_error_under = mean_squared_error(y_test_over, test_pred_under)
print(f'Modelo con grado polinomial {degree_under} (subajustado):')
print(f'  Error de Entrenamiento (MSE): {train_error_under:.4f}')
print(f'  Error de Prueba (MSE): {test_error_under:.4f}')

# Ajuste apropiado
degree_proper = 3
proper_fit_model = make_pipeline(PolynomialFeatures(degree_proper), LinearRegression())
proper_fit_model.fit(X_train_over, y_train_over)
train_pred_proper = proper_fit_model.predict(X_train_over)
test_pred_proper = proper_fit_model.predict(X_test_over)
train_error_proper = mean_squared_error(y_train_over, train_pred_proper)
test_error_proper = mean_squared_error(y_test_over, test_pred_proper)
print(f'Modelo con grado polinomial {degree_proper} (ajuste apropiado):')
print(f'  Error de Entrenamiento (MSE): {train_error_proper:.4f}')
print(f'  Error de Prueba (MSE): {test_error_proper:.4f}')
print(f'  R2 de Entrenamiento: {r2_score(y_train_over, train_pred_proper):.4f}')
print(f'  R2 de Prueba: {r2_score(y_test_over, test_pred_proper):.4f}')

Modelo con grado polinomial 1 (subajustado):
  Error de Entrenamiento (MSE): 0.0090
  Error de Prueba (MSE): 0.0115
Modelo con grado polinomial 3 (ajuste apropiado):
  Error de Entrenamiento (MSE): 0.0090
  Error de Prueba (MSE): 0.0115
  R2 de Entrenamiento: 0.1019
  R2 de Prueba: -0.1831


## Trade-Off entre Sesgo y Varianza
- **Sesgo:** Error por suposiciones simplificadas. Alto sesgo = subajuste.
- **Varianza:** Sensibilidad excesiva a los datos de entrenamiento. Alta varianza = sobreajuste.

## Validación Cruzada: Definición y Objetivo
La validación cruzada evalúa el rendimiento de un modelo dividiendo los datos en varios subconjuntos y rotando el conjunto de validación.

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.datasets import load_iris # https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html

'''
load_iris() es un dataset de ejemplo incluido en Scikit-Learn.
Este dataset contiene información sobre flores de iris y se usa comúnmente para practicar clasificación y regresión.

¿Qué contiene?

iris['data']: Matriz con las características de cada flor (largo y ancho de sépalos y pétalos).
iris['target']: Vector con la clase de cada flor (0, 1 o 2, que representan tres especies de iris).
También incluye información adicional como nombres de las clases y descripción.
Uso típico:
Se utiliza para aprender y probar algoritmos de machine learning, ya que es pequeño, limpio y bien conocido.
'''

iris = load_iris()
print(iris['data'][:5]) # muestra de los primeros 5 registros
print(iris['target'][:5]) # muestra de los primeros 5 objetivos
X_iris, y_iris = iris.data, iris.target
# Validación cruzada con K-Fold (k=5) para el dataset Iris
model_iris = LinearRegression()
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model_iris, X_iris, y_iris, cv=kf, scoring='neg_mean_squared_error')
rmse_scores = np.sqrt(-scores)
print(f'Resultados de Validación Cruzada (RMSE) con K-Fold (k=5):')
print(f'Scores para cada fold: {rmse_scores.round(4)}')
print(f'Error promedio (RMSE) en datos no vistos: {rmse_scores.mean():.4f}')
print(f'R2 del modelo: {cross_val_score(model_iris, X_iris, y_iris, cv=kf, scoring="r2").mean():.4f}')

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
Resultados de Validación Cruzada (RMSE) con K-Fold (k=5):
Scores para cada fold: [0.1926 0.2071 0.2311 0.2513 0.2186]
Error promedio (RMSE) en datos no vistos: 0.2201
R2 del modelo: 0.9240


## Beneficios de la Validación Cruzada
- Estimación robusta del rendimiento.
- Ayuda a evitar sobreajuste.
- Maximiza el uso de los datos disponibles.

## Técnicas de Validación Cruzada
- **Hold-Out:** Divide en entrenamiento y prueba una sola vez.
- **k-Fold:** Divide en k partes y rota el conjunto de validación.
- **Random Subsampling:** Divide aleatoriamente varias veces.
- **Leave-One-Out:** Cada muestra es usada una vez como prueba.

In [8]:
from sklearn.model_selection import ShuffleSplit, LeaveOneOut

# Método de Retención (Hold-Out)
X_train_hold, X_test_hold, y_train_hold, y_test_hold = train_test_split(X_iris, y_iris, test_size=0.3, random_state=42)
model_hold = LinearRegression()
model_hold.fit(X_train_hold, y_train_hold)
hold_out_error = mean_squared_error(y_test_hold, model_hold.predict(X_test_hold))
hold_out_mae = mean_absolute_error(y_test_hold, model_hold.predict(X_test_hold))

print(f'Método de Retención (Hold-Out) - Error de Prueba (MSE): {hold_out_error:.4f}')
print(f'Método de Retención (Hold-Out) - Error de Prueba (MAE): {hold_out_mae:.4f}')
print(f'Método de Retención (Hold-Out) - R2: {r2_score(y_test_hold, model_hold.predict(X_test_hold)):.4f}')

Método de Retención (Hold-Out) - Error de Prueba (MSE): 0.0387
Método de Retención (Hold-Out) - Error de Prueba (MAE): 0.1533
Método de Retención (Hold-Out) - R2: 0.9442


In [9]:
# Validación Cruzada con Random Subsampling
ss = ShuffleSplit(n_splits=10, test_size=0.2, random_state=42)
random_subsampling_scores = cross_val_score(model_iris, X_iris, y_iris, cv=ss, scoring='neg_mean_squared_error')
random_subsampling_mae_scores = -random_subsampling_scores  # Convertir a valores positivos

print(f'Random Subsampling (10 iteraciones) - Error promedio (RMSE): {np.sqrt(-random_subsampling_scores).mean():.4f}')
print(f'Random Subsampling (10 iteraciones) - MAE por iteración: {random_subsampling_mae_scores.round(4)}')
print(f'Random Subsampling (10 iteraciones) - Promedio MAE: {random_subsampling_mae_scores.mean():.4f}')
print(f'Random Subsampling (10 iteraciones) - R2: {cross_val_score(model_iris, X_iris, y_iris, cv=ss, scoring="r2").mean():.4f}')

Random Subsampling (10 iteraciones) - Error promedio (RMSE): 0.2155
Random Subsampling (10 iteraciones) - MAE por iteración: [0.0371 0.0407 0.0443 0.0541 0.0591 0.0442 0.0532 0.0341 0.0456 0.0555]
Random Subsampling (10 iteraciones) - Promedio MAE: 0.0468
Random Subsampling (10 iteraciones) - R2: 0.9250


In [10]:
# Validación Cruzada con Leave-One-Out
loo = LeaveOneOut()
loo_scores = cross_val_score(model_iris, X_iris, y_iris, cv=loo, scoring='neg_mean_squared_error')
loo_mae_scores = -loo_scores  # Convertir a valores positivos
print(f'Leave-One-Out (LOO) - Error promedio (RMSE): {np.sqrt(-loo_scores).mean():.4f}')
# print(f'Leave-One-Out (LOO) - MAE por muestra: {loo_mae_scores.round(4)}')
print(f'Leave-One-Out (LOO) - Promedio MAE: {loo_mae_scores.mean():.4f}')
print("Nota: El R² en Leave-One-Out puede no ser representativo debido al tamaño mínimo de los folds.")
# print(f'Leave-One-Out (LOO) - R2: {cross_val_score(model_iris, X_iris, y_iris, cv=loo, scoring="r2").mean():.4f}')

Leave-One-Out (LOO) - Error promedio (RMSE): 0.1709
Leave-One-Out (LOO) - Promedio MAE: 0.0495
Nota: El R² en Leave-One-Out puede no ser representativo debido al tamaño mínimo de los folds.


In [11]:
# Validación Cruzada k-Fold
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
kfold_scores = cross_val_score(model_iris, X_iris, y_iris, cv=kf, scoring='neg_mean_squared_error')
mae_scores = -kfold_scores  # Convertir a valores positivos
print(f'k-Fold (k=5) - Error promedio (RMSE): {np.sqrt(-kfold_scores).mean():.4f}')
print(f'k-Fold (k=5) - MAE por fold: {mae_scores.round(4)}')
print(f'k-Fold (k=5) - Promedio MAE: {mae_scores.mean():.4f}')
print(f'k-Fold (k=5) - R2: {cross_val_score(model_iris, X_iris, y_iris, cv=kf, scoring="r2").mean():.4f}')

k-Fold (k=5) - Error promedio (RMSE): 0.2201
k-Fold (k=5) - MAE por fold: [0.0371 0.0429 0.0534 0.0632 0.0478]
k-Fold (k=5) - Promedio MAE: 0.0489
k-Fold (k=5) - R2: 0.9240


## Implementación en Scikit-Learn
- Importa las librerías necesarias.
- Carga y prepara los datos.
- Selecciona el método de validación cruzada adecuado.

## Evaluación y Comparación
Utiliza `cross_val_score` para comparar el rendimiento de diferentes métodos de validación cruzada.