---
# Guía Redes Neuronales Densas

En esta guía abordaremos los siguientes tópicos:
- Preparación de datos y codificación One-Hot


### Preparación de datos y codificación One-Hot

A menudo, se recomienda realizar preparaciones de los datos de formas específicas antes de ajustar un modelo de machine learning. ¿Por qué? porque algunos algoritmos no pueden trabajar con datos categóricos directamente. Por ejemplo, un arbol de decisión puede aprender directamente de la data categórica sin necesidad de transformación de data (aunque esto podría depender de la implementación). Sin embargo, existen varios algoritmos que no pueden operar directamente con los datos categóricos y que requieren que, tanto las variables de entrada como las de salida, sean numéricas.

**¿Cómo convertir data categórica en data numérica?**

Esto conlleva dos etapas:
- Codificación entera
- Codificación One-Hot



**Codificación Entera**

Consiste en asignar un valor enterno a cada categoría. Los valores enteros tienen una relación ordenada de cada valor, lo cual puede ser útil para que los algoritmos de machine learning puedan entender la relación entre categorías. Por ejemplo, variables ordinales tales como "grado de satisfacción" podría ser suficiente utilizar una codificación entera. 

In [15]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [5]:
# Ejemplo de una codificación entera
satisfaccion = ['malo','mas o menos','bueno','bueno','malo','bueno','malo','mas o menos']

In [6]:
# Label Encoding
label_encoder = LabelEncoder()
label_encoder.fit(satisfaccion)
label_encoded = label_encoder.transform(satisfaccion)

print("Valores con condificacion entera:",label_encoded)
print("Clases:", label_encoder.classes_)

Valores con condificacion entera: [1 2 0 0 1 0 1 2]
Clases: ['bueno' 'malo' 'mas o menos']


El atributo `classes_` contiene una lista de las clases únicas encontradas en los datos de entrenamiento, ordenadas alfabéticamente o por orden de aparición en los datos, dependiendo de la implementación específica de LabelEncoder. Estos son los valores que el LabelEncoder ha asignado a las clases después de ajustarse a los datos. Puedes utilizar estos valores para entender cómo han sido codificadas las clases. En este caso, no se cumple el propósito de darle un ordenamiento lógico a los niveles de satisfacción, pero esto se puede arreglar de la siguiente forma.

In [17]:
# Definir el mapeo entre las clases y los valores asignados
mapeo_clases = {'malo': 0, 'mas o menos': 1, 'bueno': 2}

# Aplicar el mapeo al LabelEncoder
label_encoder.classes_ = np.array([k for k, v in sorted(mapeo_clases.items(), key=lambda item: item[1])])

# ajustamos nuevamente el encoder
label_encoded = label_encoder.transform(satisfaccion)


print("Valores con condificacion entera:",label_encoded)
print("Clases:", label_encoder.classes_)

Valores con condificacion entera: [0 1 2 2 0 2 0 1]
Clases: ['malo' 'mas o menos' 'bueno']


**Codificación One-Hot**

La codificación One-Hot (también conocida como one-of-K encoding o dummy encoding) es una técnica utilizada en el procesamiento de datos para convertir variables categóricas en una forma que puede ser proporcionada a algoritmos de aprendizaje automático para mejorar su rendimiento.

En la codificación One-Hot, cada categoría única en la variable categórica se convierte en una nueva característica binaria (o "dummy"), donde cada característica representa una categoría distinta y tiene un valor de 1 si la observación pertenece a esa categoría y 0 en caso contrario. De esta manera, se crea una matriz de características binarias donde cada fila representa una observación y cada columna representa una categoría.

Por ejemplo, supongamos que tienes una variable categórica "Color" con tres categorías: "Rojo", "Verde" y "Azul". La codificación One-Hot convertiría esta variable en tres nuevas características binarias:

- "Rojo": [1, 0, 0]
- "Verde": [0, 1, 0]
- "Azul": [0, 0, 1]

Estas características se utilizan luego como entradas para entrenar un modelo de aprendizaje automático. La codificación One-Hot es útil porque permite que los algoritmos de aprendizaje automático trabajen con variables categóricas sin asumir ningún orden o relación entre las categorías, lo que puede ser importante en muchas aplicaciones.

En Python, puedes realizar la codificación One-Hot utilizando funciones de bibliotecas como scikit-learn o pandas. Por ejemplo, en scikit-learn, puedes utilizar la clase OneHotEncoder, mientras que en pandas, puedes usar la función get_dummies.


In [20]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
# Ejemplo de características categóricas
colores = [['Rojo'], ['Verde'], ['Azul'], ['Rojo'], ['Verde']]

In [24]:
# Inicializar y ajustar el OneHotEncoder
encoder = OneHotEncoder()
encoder.fit(colores)

# Transformar las características utilizando el OneHotEncoder
categorias_codificadas = encoder.transform(colores)

# Convertir las características codificadas a un array NumPy
categorias_codificadas_array = categorias_codificadas.toarray()

print("Características codificadas:")
print(categorias_codificadas_array)

print("Dimensiones arreglo codificado:", categorias_codificadas_array.shape)

print("Categirías:", encoder.categories_)

Características codificadas:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimensiones arreglo codificado: (5, 3)
Categirías: [array(['Azul', 'Rojo', 'Verde'], dtype=object)]


Ahora resolveremos el problema de la flor iris, realizando una codificación one hot de la variable objetivo (species)

In [27]:
import pandas as pd

In [29]:
from sklearn.datasets import load_iris

In [31]:
bunch = load_iris()
df = pd.DataFrame(bunch.data, columns=bunch.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [33]:
X = df
y = bunch.target

**Preprocesamiento de los datos**

En este caso, realice los siguientes preprocesamientos:

- Escalamiento de los datos
- Codificación one-hot para la variable objetivo

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Escalamiento de las variables de entrada
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Codificación one-hot de la variable objetivo
y_reshaped = y.reshape(-1, 1)
ohe = OneHotEncoder(sparse_output=False)
y_onehot = ohe.fit_transform(y_reshaped)

print("Shape X_scaled:", X_scaled.shape)
print("Shape y_onehot:", y_onehot.shape)

In [ ]:
# Visualizar primeras filas de la codificación one-hot
y_onehot[:5]

**Validación cruzada**

Divida el set de datos en traun y test

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_onehot,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

**Diseño Arquitectura**

Ahora diseñe una arquitectura para la red neuronal similar a la utilizada en la actividad anterior.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

input_dim = X_train.shape[1]
n_classes = y_train.shape[1]

model = Sequential()
model.add(Dense(4, activation='tanh', input_shape=(input_dim,)))
model.add(Dense(10, activation='tanh'))
model.add(Dense(8, activation='tanh'))
model.add(Dense(n_classes, activation='softmax'))

optimizer = Adam(learning_rate=0.02)
model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

**Entrenamiento ANN**

Entrene la red definida

**Realizando predicciones**

Realice predicciones para la siguiente medición:

    [4.7,	3.2, 	1.3, 	0.2]

In [ ]:
import numpy as np

p1 = [4.7, 3.2, 1.3, 0.2]

# Escalamos el nuevo punto con el mismo scaler
p1_arr = np.array(p1).reshape(1, -1)
p1_scaled = scaler.transform(p1_arr)

# Predicción de probabilidades y clase
p1_proba = model.predict(p1_scaled)
p1_class = np.argmax(p1_proba, axis=1)[0]
p1_species = bunch.target_names[p1_class]

print("Probabilidades:", p1_proba)
print("Clase predicha (índice):", p1_class)
print("Especie predicha:", p1_species)

In [ ]:
# realice prediccione en el set de test
y_pred_proba = model.predict(X_test)
y_pred = np.argmax(y_pred_proba, axis=1)
y_test_labels = np.argmax(y_test, axis=1)

y_pred[:10]

**Métricas de evaluación**

Calcule las métricas de evaluación al modelo entrenado (score, matriz de confusión)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

cm = confusion_matrix(y_test_labels, y_pred)
print("Matriz de confusión:\n", cm)

print("\nReporte de clasificación:\n")
print(classification_report(y_test_labels, y_pred))

acc = accuracy_score(y_test_labels, y_pred)
print("\nAccuracy:", acc)

In [ ]:
# Score del modelo en el conjunto de test
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print("Score en test - loss:", test_loss)
print("Score en test - accuracy:", test_acc)

### Conclusiones

Escriba acá sus conclusiones y reflexiones.

In [ ]:
# conclusiones acá




---